/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilerprogram;

import java.io.*;
import java.util.*;
import javax.swing.JFileChooser;

/**
 *
 * @author h_laessig
 */
public class MainFrame extends javax.swing.JFrame {

    String fileName;
    String programName;
    String folderName;
    String inputFile;
    String studentName;
    ArrayList<String> batchOutput;
    ArrayList<String> studentNames;
    ArrayList<String> compileResults;
    ArrayList<String> inputs = new ArrayList<>();

    JFileChooser chooser;
    String chooserTitle;

    RunBatch batch = new RunBatch();
    RunSingle single = new RunSingle();

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        buttonGroupSingle = new javax.swing.ButtonGroup();
        buttonGroupBatch = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        singlePanel = new javax.swing.JPanel();
        singleUpperPanel = new javax.swing.JPanel();
        selectFile = new javax.swing.JButton();
        singleDirectoryField = new javax.swing.JTextField();
        selectTxt = new javax.swing.JButton();
        txtDirectory = new javax.swing.JTextField();
        singleArgsCheck = new javax.swing.JCheckBox();
        singleScannerCheck = new javax.swing.JCheckBox();
        selectInputsSingleLabel = new javax.swing.JLabel();
        programTextField = new javax.swing.JTextField();
        folderStudentSubdirectoriesLabel = new javax.swing.JLabel();
        txtFileInputsLabel = new javax.swing.JLabel();
        programNameLabel = new javax.swing.JLabel();
        studentCombo = new javax.swing.JComboBox();
        selectStudentLabel = new javax.swing.JLabel();
        singleLowerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayResults = new javax.swing.JTextArea();
        compileSingle = new javax.swing.JButton();
        runSingle = new javax.swing.JButton();
        OutputsLabel = new javax.swing.JLabel();
        batchPanel = new javax.swing.JPanel();
        batchUpperPanel = new javax.swing.JPanel();
        folderList = new javax.swing.JButton();
        directoryField = new javax.swing.JTextField();
        inputsSelection = new javax.swing.JButton();
        inputsField = new javax.swing.JTextField();
        selectInputsBatchLabel = new javax.swing.JLabel();
        batchArgsCheck = new javax.swing.JCheckBox();
        batchScannerCheck = new javax.swing.JCheckBox();
        programNameField = new javax.swing.JTextField();
        selectBatchFolderLabel = new javax.swing.JLabel();
        inputTextFileLabel = new javax.swing.JLabel();
        javaProgramLabel = new javax.swing.JLabel();
        programNameButton = new javax.swing.JButton();
        batchLowerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        batchCompileText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchRunText = new javax.swing.JTextArea();
        CompileBatch = new javax.swing.JButton();
        runBatch = new javax.swing.JButton();
        CompileOutputLabel = new javax.swing.JLabel();
        RunOutputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        singleUpperPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        selectFile.setText("Select Folder");
        selectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileActionPerformed(evt);
            }
        });

        selectTxt.setText("Select Inputs");
        selectTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTxtActionPerformed(evt);
            }
        });

        buttonGroupSingle.add(singleArgsCheck);
        singleArgsCheck.setText("ARGS Inputs");

        buttonGroupSingle.add(singleScannerCheck);
        singleScannerCheck.setSelected(true);
        singleScannerCheck.setText("Scanner Inputs");

        selectInputsSingleLabel.setText("Select which inputs the program uses (doesnt work)");

        programTextField.setToolTipText("Example: ArrayLoops");

        folderStudentSubdirectoriesLabel.setText("Select folder containing student subdirectories");

        txtFileInputsLabel.setText("Select .txt file with inputs");

        programNameLabel.setText("Enter name of program to be ran");

        studentCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Choose folder first"}));

        selectStudentLabel.setText("Select student you would like to run program for");

        javax.swing.GroupLayout singleUpperPanelLayout = new javax.swing.GroupLayout(singleUpperPanel);
        singleUpperPanel.setLayout(singleUpperPanelLayout);
        singleUpperPanelLayout.setHorizontalGroup(
                singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singleUpperPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                                        .addComponent(selectFile, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(folderStudentSubdirectoriesLabel)
                                                .addComponent(singleDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, singleUpperPanelLayout.createSequentialGroup()
                                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                                                        .addComponent(selectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtFileInputsLabel)))
                                                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                                                        .addGap(69, 69, 69)
                                                        .addComponent(singleArgsCheck)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(singleScannerCheck))
                                                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                                                        .addGap(26, 26, 26)
                                                        .addComponent(selectInputsSingleLabel)))
                                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                                                        .addGap(32, 32, 32)
                                                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(programTextField)
                                                                .addComponent(studentCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                                                                        .addComponent(programNameLabel)
                                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singleUpperPanelLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(selectStudentLabel)
                                                        .addGap(15, 15, 15)))))
                        .addGap(91, 91, 91))
        );
        singleUpperPanelLayout.setVerticalGroup(
                singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(singleUpperPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(folderStudentSubdirectoriesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(selectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(singleDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFileInputsLabel)
                                .addComponent(programNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(programTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selectTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(selectInputsSingleLabel)
                                .addComponent(selectStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(singleUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(singleArgsCheck)
                                .addComponent(singleScannerCheck)
                                .addComponent(studentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
        );

        singleLowerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        // displayResults.setSize(10, 10);
        // displayResults.setColumns(1);
        // displayResults.setRows(1);
        jScrollPane1.setViewportView(displayResults);

        compileSingle.setText("Compile");
        compileSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileActionPerformed(evt, "Single");
            }
        });

        runSingle.setText("Run");
        runSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt, "Single");
            }
        });

        OutputsLabel.setText("Outputs");

        javax.swing.GroupLayout singleLowerPanelLayout = new javax.swing.GroupLayout(singleLowerPanel);
        singleLowerPanel.setLayout(singleLowerPanelLayout);
        singleLowerPanelLayout.setHorizontalGroup(
                singleLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singleLowerPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                .addGroup(singleLowerPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(compileSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                .addGroup(singleLowerPanelLayout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(OutputsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        singleLowerPanelLayout.setVerticalGroup(
                singleLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(singleLowerPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(OutputsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(singleLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(compileSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(runSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout singlePanelLayout = new javax.swing.GroupLayout(singlePanel);
        singlePanel.setLayout(singlePanelLayout);
        singlePanelLayout.setHorizontalGroup(
                singlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(singlePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(singlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(singleUpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(singleLowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
        );
        singlePanelLayout.setVerticalGroup(
                singlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(singlePanelLayout.createSequentialGroup()
                        .addComponent(singleUpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singleLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Single", singlePanel);

        batchUpperPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        folderList.setText("Select Folder");
        folderList.setMaximumSize(new java.awt.Dimension(137, 29));
        folderList.setMinimumSize(new java.awt.Dimension(137, 29));
        folderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderListActionPerformed(evt);
            }
        });

        inputsSelection.setText("Select Inputs");
        inputsSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputsSelectionActionPerformed(evt);
            }
        });

        selectInputsBatchLabel.setText("Select which inputs the program uses (doesnt work yet)");

        buttonGroupBatch.add(batchArgsCheck);
        batchArgsCheck.setText("ARGS Inputs");

        buttonGroupBatch.add(batchScannerCheck);
        batchScannerCheck.setSelected(true);
        batchScannerCheck.setText("Scanner Inputs");

        programTextField.setToolTipText("Example: ArrayLoops");

        selectBatchFolderLabel.setText("Select folder containing batch folders to process");

        inputTextFileLabel.setText("Select text file containing inputs");

        javaProgramLabel.setText("Enter name of java program");

        programNameButton.setText("Enter");
        programNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout batchUpperPanelLayout = new javax.swing.GroupLayout(batchUpperPanel);
        batchUpperPanel.setLayout(batchUpperPanelLayout);
        batchUpperPanelLayout.setHorizontalGroup(
                batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(batchUpperPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(folderList, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputsSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(batchUpperPanelLayout.createSequentialGroup()
                                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(batchUpperPanelLayout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(inputTextFileLabel))
                                                .addGroup(batchUpperPanelLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(inputsField, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        //.addComponent(programNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(programNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(javaProgramLabel))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(batchUpperPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(selectBatchFolderLabel)
                                                .addComponent(directoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(batchUpperPanelLayout.createSequentialGroup()
                                                                .addComponent(batchArgsCheck)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(batchScannerCheck))
                                                        .addComponent(selectInputsBatchLabel)))
                                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        batchUpperPanelLayout.setVerticalGroup(
                batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(batchUpperPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(selectBatchFolderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(folderList, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(directoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputTextFileLabel)
                                .addComponent(javaProgramLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputsSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputsField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(programNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        //  .addComponent(programNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                        .addGap(31, 31, 31)
                        .addComponent(selectInputsBatchLabel)
                        // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(batchUpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(batchArgsCheck)
                                .addComponent(batchScannerCheck))
                        .addContainerGap())
        );

        batchLowerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        batchCompileText.setEditable(false);
        batchCompileText.setColumns(20);
        batchCompileText.setLineWrap(true);
        batchCompileText.setRows(5);
        jScrollPane3.setViewportView(batchCompileText);

        batchRunText.setEditable(false);
        batchRunText.setColumns(20);
        batchRunText.setRows(5);
        jScrollPane2.setViewportView(batchRunText);

        CompileBatch.setText("CompileBatch");
        CompileBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileActionPerformed(evt, "Batch");
            }
        });

        runBatch.setText("RunBatch");
        runBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt, "Batch");
            }
        });

        CompileOutputLabel.setText("Compiler Output");

        RunOutputLabel.setText("Run Output");

        javax.swing.GroupLayout batchLowerPanelLayout = new javax.swing.GroupLayout(batchLowerPanel);
        batchLowerPanel.setLayout(batchLowerPanelLayout);
        batchLowerPanelLayout.setHorizontalGroup(
                batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(batchLowerPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(CompileBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, batchLowerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CompileOutputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RunOutputLabel)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
        );
        batchLowerPanelLayout.setVerticalGroup(
                batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(batchLowerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CompileOutputLabel)
                                .addComponent(RunOutputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(batchLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(runBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CompileBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
        );

        javax.swing.GroupLayout batchPanelLayout = new javax.swing.GroupLayout(batchPanel);
        batchPanel.setLayout(batchPanelLayout);
        batchPanelLayout.setHorizontalGroup(
                batchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(batchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(batchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(batchLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(batchUpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        batchPanelLayout.setVerticalGroup(
                batchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(batchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(batchUpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batchLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
        );

        jTabbedPane2.addTab("Batch", batchPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>                        

    private void selectFileActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //Folder chooser
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(chooserTitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION && chooser.getSelectedFile() != null) {
            folderName = (chooser.getSelectedFile().toString());
            singleDirectoryField.setText(folderName);

            //Get list of students in folder
            studentNames = batch.getFolders(folderName);
            studentCombo.removeAllItems();

            for (int i = 0; i < studentNames.size(); i++) {
                studentCombo.addItem(studentNames.get(i));
            }
        } else {
            folderName = "";
            singleDirectoryField.setText("No Selection");
        }

    }                                          

    private void runActionPerformed(java.awt.event.ActionEvent evt, String event) {                                    

        if (event.equals("Single")) {
            studentName = studentCombo.getSelectedItem().toString();

            if (folderName == null || fileName == null || studentName == null) {
                displayResults.setText("Missing required field");
            } else {
                String results = single.getProcessOutput(folderName, fileName, studentName, inputs);
                displayResults.setText(results);
            }
        }
        if (event.equals("Batch")) {

            if (folderName == null || programName == null) {
                batchRunText.setText("Required fields missing");
            } else {
                //Run batch run
                batchOutput = batch.getBatchOutput(inputs, folderName, programName);
                for (int i = 0; i < batchOutput.size(); i++) {
                    batchRunText.append(studentNames.get(i) + "\n" + batchOutput.get(i) + "\n\n");
                }
            }
        }

    }                                   

    private void compileActionPerformed(java.awt.event.ActionEvent evt, String event) {                                        

        if (event.equals("Single")) {
            fileName = programTextField.getText();
            int didCompile = 0;
            if (!fileName.isEmpty()) {
                didCompile = single.singleCompile(fileName);
            }

            if (didCompile == 1) {
                displayResults.setText("Compiled Succesfully");
            } else {
                displayResults.setText("File Failed to compile");
            }
        }
        if (event.equals("Batch")) {
            programName = programNameField.getText();

            if (folderName == null || programName == null) {
                batchCompileText.setText("Required fields missing");
            } else {
                //Run batch compile
                compileResults = batch.batchCompile(folderName, programName);

                for (int i = 0; i < compileResults.size(); i++) {
                    batchCompileText.append(compileResults.get(i) + "\n");
                }
            }
        }
    }                                       

    private void folderListActionPerformed(java.awt.event.ActionEvent evt) {                                           

        //Folder chooser
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(chooserTitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION && chooser.getSelectedFile() != null) {
            folderName = (chooser.getSelectedFile().toString());
            directoryField.setText(folderName);

            //Get list of students in folder
            studentNames = batch.getFolders(folderName);
            int numberOfStudents = studentNames.size();
        } else {
            directoryField.setText("No Selection");
            folderName = "";
        }

    }                                          

    private void selectTxtActionPerformed(java.awt.event.ActionEvent evt) {                                          

        //Display file chooser for user to select inputs.txt
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setDialogTitle("Choose a file");
        singlePanel.add(fileChooser);
        fileChooser.setVisible(true);

        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION && fileChooser.getSelectedFile() != null) {
            inputFile = fileChooser.getSelectedFile().toString();
            txtDirectory.setText(inputFile);
        } else {
            txtDirectory.setText("No Selection");
            inputFile = "";
        }

        // This will reference one line at a time
        String line = null;

        try {
            FileReader fileReader = new FileReader(inputFile);

            BufferedReader bufferedReader = new BufferedReader(fileReader);

            while ((line = bufferedReader.readLine()) != null) {
                inputs.add(line);
            }

            bufferedReader.close();
        } catch (FileNotFoundException ex) {
            System.out.println(
                    "Unable to open file '"
                    + fileName + "'");
        } catch (IOException ex) {
            System.out.println(
                    "Error reading file '"
                    + fileName + "'");
            // Or we could just do this: 
            // ex.printStackTrace();
        }

    }                                         

    private void inputsSelectionActionPerformed(java.awt.event.ActionEvent evt) {                                                

        //Display file chooser for user to select inputs.txt
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose a file");
        fileChooser.setCurrentDirectory(new java.io.File("."));

        singlePanel.add(fileChooser);
        fileChooser.setVisible(true);

        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION && fileChooser.getSelectedFile() != null) {
            inputFile = fileChooser.getSelectedFile().toString();
            inputsField.setText(inputFile);
        } else {
            inputsField.setText("No Selection");
            inputFile = "";
        }

        // This will reference one line at a time
        String line = null;

        try {
            FileReader fileReader = new FileReader(inputFile);

            BufferedReader bufferedReader = new BufferedReader(fileReader);

            while ((line = bufferedReader.readLine()) != null) {
                System.out.println(Integer.parseInt(line));
                inputs.add(line);
            }

            bufferedReader.close();
        } catch (FileNotFoundException ex) {
            System.out.println(
                    "Unable to open file '"
                    + fileName + "'");
        } catch (IOException ex) {
            System.out.println(
                    "Error reading file '"
                    + fileName + "'");
            // Or we could just do this: 
            // ex.printStackTrace();
        }
    }                                               

    private void programNameButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  

        System.out.println("Folder Name: " + folderName);
        System.out.println("Program Name: " + programName);
        if (folderName != null || !folderName.equals("") || programName != null) {
            programName = programNameField.getText();
            batchCompileText.setText("Batch will run all programs named: " + programName + "\nContained within the folder: " + folderName);
        } else {
            batchCompileText.setText("Please select a folder first");
        }
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CompileBatch;
    private javax.swing.JCheckBox batchArgsCheck;
    private javax.swing.JTextArea batchCompileText;
    private javax.swing.JTextArea batchRunText;
    private javax.swing.JCheckBox batchScannerCheck;
    private javax.swing.ButtonGroup buttonGroupSingle;
    private javax.swing.ButtonGroup buttonGroupBatch;
    private javax.swing.JButton compileSingle;
    private javax.swing.JTextField directoryField;
    private javax.swing.JTextArea displayResults;
    private javax.swing.JButton folderList;
    private javax.swing.JTextField inputsField;
    private javax.swing.JButton inputsSelection;
    private javax.swing.JLabel OutputsLabel;
    private javax.swing.JLabel javaProgramLabel;
    private javax.swing.JLabel programNameLabel;
    private javax.swing.JLabel selectStudentLabel;
    private javax.swing.JLabel selectInputsSingleLabel;
    private javax.swing.JLabel folderStudentSubdirectoriesLabel;
    private javax.swing.JLabel txtFileInputsLabel;
    private javax.swing.JLabel CompileOutputLabel;
    private javax.swing.JLabel RunOutputLabel;
    private javax.swing.JLabel selectInputsBatchLabel;
    private javax.swing.JLabel selectBatchFolderLabel;
    private javax.swing.JLabel inputTextFileLabel;
    private javax.swing.JPanel singlePanel;
    private javax.swing.JPanel batchPanel;
    private javax.swing.JPanel singleUpperPanel;
    private javax.swing.JPanel singleLowerPanel;
    private javax.swing.JPanel batchUpperPanel;
    private javax.swing.JPanel batchLowerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton programNameButton;
    private javax.swing.JTextField programNameField;
    private javax.swing.JTextField programTextField;
    private javax.swing.JButton runBatch;
    private javax.swing.JButton runSingle;
    private javax.swing.JButton selectFile;
    private javax.swing.JButton selectTxt;
    private javax.swing.JCheckBox singleArgsCheck;
    private javax.swing.JTextField singleDirectoryField;
    private javax.swing.JCheckBox singleScannerCheck;
    private javax.swing.JComboBox studentCombo;
    private javax.swing.JTextField txtDirectory;
    // End of variables declaration                   
}


